# Generated by Django 5.1.4
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('completed', 'Completed')],
                    default='pending',
                    max_length=20,
                )),
                ('priority', models.CharField(
                    choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')],
                    default='medium',
                    max_length=20,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tasks',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'app_label': 'core',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('planned_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')],
                    default='active',
                    max_length=20,
                )),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='focus_sessions',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('task', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='focus_sessions',
                    to='core.taskmodel',
                )),
            ],
            options={
                'app_label': 'core',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='blocked_sites',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'app_label': 'core',
                'ordering': ['domain'],
                'unique_together': {('owner', 'domain')},
            },
        ),
    ]
